/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.8.0.
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as chat from "../chat.js";
import type * as ingest_embed from "../ingest/embed.js";
import type * as langchain_db from "../langchain/db.js";
import type * as myFunctions from "../myFunctions.js";
import type * as pdf from "../pdf.js";
import type * as resume from "../resume.js";
import type * as utils from "../utils.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  chat: typeof chat;
  "ingest/embed": typeof ingest_embed;
  "langchain/db": typeof langchain_db;
  myFunctions: typeof myFunctions;
  pdf: typeof pdf;
  resume: typeof resume;
  utils: typeof utils;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
